import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr';

interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.projects": "Projets",
    "nav.contact": "Contact",
    "home.hero.badge": "Expertise Industrielle",
    "home.hero.title": "Solutions d'Automatisme",
    "home.hero.title.accent": " Premium",
    "home.hero.desc": "SOMATISME propose des solutions d'automatisme industriel, régulation, installation électrique et maintenance pour les entreprises B2B modernes.",
    "home.hero.cta.quote": "Demander un devis",
    "home.hero.cta.discover": "Découvrir nos services",
    "home.process.title": "Notre Méthodologie",
    "home.process.subtitle": "Un accompagnement rigoureux de la conception à la maintenance.",
    "home.why.title": "Pourquoi SOMATISME ?",
    "home.why.subtitle": "L'excellence technique au service de votre productivité.",
    "home.why.item1": "Expertise Multimarque (Siemens, Schneider)",
    "home.why.item2": "Réactivité garantie : Intervention sous 24h/48h",
    "home.why.item3": "Conformité totale aux normes industrielles (NFC, CEI)",
    "home.why.item4": "Maîtrise des technologies Industrie 4.0",
    "home.process.step1.title": "Audit & Analyse",
    "home.process.step1.desc": "Étude approfondie de vos besoins techniques et contraintes de production.",
    "home.process.step2.title": "Conception",
    "home.process.step2.desc": "Définition de l'architecture logicielle et matérielle optimisée.",
    "home.process.step3.title": "Déploiement",
    "home.process.step3.desc": "Installation sur site, programmation et tests rigoureux.",
    "home.process.step4.title": "Maintenance",
    "home.process.step4.desc": "Suivi post-projet, assistance 24/7 et optimisation continue.",
    "about.hero.title": "À propos de SOMATISME",
    "about.hero.subtitle": "Leader en solutions d'automatisme industriel depuis plus de 15 ans",
    "about.sectors.title": "Des secteurs d'activité très diversifiés",
    "about.sectors.subtitle": "Une expertise transversale au service de l'industrie.",
    "about.infra.title": "Infrastructure & Moyens Techniques",
    "about.infra.subtitle": "Un environnement de travail conçu pour l'excellence industrielle.",
    "about.infra.be.title": "Bureau d'Études",
    "about.infra.be.desc": "Ingénierie avancée équipée des derniers logiciels de CAO/DAO (EPLAN, AutoCAD). Nous réalisons des études de sélectivité, des bilans de puissance et le développement software sur des plateformes de simulation dédiées.",
    "about.infra.atelier.title": "Atelier de Montage",
    "about.infra.atelier.desc": "Atelier spécialisé de Mohammedia pour la réalisation d'armoires, pupitres et TGBT de forte puissance. Chaque réalisation subit des tests de continuité et des protocoles FAT (Factory Acceptance Test) rigoureux.",
    "about.growth.title": "Une croissance régulière et maîtrisée",
    "about.growth.desc": "Depuis sa création, SOMATISME a su maintenir une trajectoire ascendante en investissant continuellement dans le capital humain et les outils technologiques de pointe.",
    "about.finance.title": "Un bilan particulièrement sain",
    "about.finance.desc": "La solidité de notre structure financière nous permet d'aborder sereinement des projets de grande envergure. Nous garantissons à nos partenaires une pérennité totale dans nos engagements.",
    "about.culture.title": "Et surtout … Une culture d’entreprise",
    "about.culture.subtitle": "Pour une satisfaction partagée et une relation confiante et pérenne avec nos clients.",
    "about.culture.passion.title": "Passion",
    "about.culture.passion.desc": "L’Automatisme industriel et les Techniques du temps réel.",
    "about.culture.innovation.title": "Innovation",
    "about.culture.innovation.desc": "Recherche et Innovation constante.",
    "about.culture.service.title": "Service",
    "about.culture.service.desc": "Service et Disponibilité sur-mesure.",
    "about.culture.integrity.title": "Intégrité",
    "about.culture.integrity.desc": "Intégrité et Indépendance d’esprit.",
    "about.partners.title": "Nos Partenaires",
    "about.partners.subtitle": "Ils nous font confiance pour la maîtrise de leurs procédés.",
    "cta.contact": "Nous contacter",
    "cta.ready": "Prêt à collaborer avec nous ?",
    "sector.agro": "Agro-alimentaire",
    "sector.auto": "Automobile",
    "sector.chimie": "Chimie",
    "sector.ciment": "Cimenteries et Carrières",
    "sector.medical": "Médical",
    "sector.metallurgie": "Métallurgie",
    "sector.micro": "Micro-électronique",
    "sector.pharmacie": "Pharmacie",
    "sector.plasturgie": "Plasturgie",
    "sector.energie": "Production d’énergie",
    "sector.siderurgie": "Sidérurgie",
    "sector.sante": "Santé",
    "sector.eau": "Traitement de l’eau",
    "services.hero.title": "Nos Services",
    "services.hero.subtitle": "Solutions d'ingénierie complètes pour l'excellence opérationnelle.",
    "services.nav.title": "Navigation Rapide",
    "services.nav.desc": "Cliquez sur un service pour y accéder ou quittez la zone pour lire les détails.",
    "services.quality.title": "Engagement Qualité & Sécurité",
    "services.quality.desc": "La rigueur technique est au cœur de chaque intervention.",
    "services.quality.item1": "Conformité stricte aux normes NFC 15-100 et CEI 61131-3.",
    "services.quality.item2": "Tests FAT (Factory Acceptance Test) systématiques en atelier.",
    "services.quality.item3": "Protocoles de mise en service SAT (Site Acceptance Test) documentés.",
    "services.quality.item4": "Habilitations électriques et sécurité machine (Directive 2006/42/CE).",
    "services.cta.title": "Besoin d'une solution personnalisée ?",
    "services.standards.title": "Normes & Standards",
    "services.standards.desc": "Toutes nos réalisations sont conformes aux normes internationales strictes : NFC 15-100, CEI 61131, et directives machines 2006/42/CE.",
    "services.brands.title": "Expertise Systèmes",
    "services.cta.desc": "Contactez nos experts pour discuter de vos besoins spécifiques",
    "services.more": "En savoir plus",
    "service.conseil.title": "Conseil & Ingénierie",
    "service.automation.title": "Automatisme Industriel",
    "service.electrical.title": "Installation Électrique",
    "service.maintenance.title": "Assistance Technique",
    "service.formation.title": "Formation",
    "service.realisation.title": "Réalisation sur Site",
    "service.realisation.hero": "La maîtrise technique et la tenue des délais pour vos projets industriels.",
    "service.realisation.domains.title": "Domaines d'Intervention",
    "service.conseil.feature1.title": "Aide à la décision",
    "service.conseil.feature1.desc": "Analyses comparatives et évaluations techniques pour sécuriser vos investissements.",
    "service.conseil.feature2.title": "Innovation",
    "service.conseil.feature2.desc": "Recherche de solutions techniques en rupture pour booster votre productivité.",
    "service.conseil.feature3.title": "Conformité",
    "service.conseil.feature3.desc": "Rédaction de cahiers des charges (APD/APS) alignés sur les standards industriels.",
    "service.conseil.item1": "Expertises et Diagnostics",
    "service.conseil.item2": "Études de faisabilité technique",
    "service.conseil.cta": "Besoin d'un diagnostic technique approfondi ?",
    "service.conseil.btn": "Demander une expertise",
    "contact.hero.title": "Nous Contacter",
    "contact.hero.subtitle": "Parlez-nous de votre projet. Nos experts sont prêts à vous aider.",
    "contact.info.title": "Informations de Contact",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.address": "Adresse",
    "contact.info.hq": "Siège Social",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Appartement N°1, Mohammedia",
    "contact.form.name": "Nom complet *",
    "contact.form.email": "Email *",
    "contact.form.submit": "Envoyer le message",
    "contact.form.submitting": "Envoi en cours...",
    "contact.form.privacy": "Vos données sont traitées en toute confidentialité conformément à la politique de protection des données industrielles.",
    "contact.form.required": "Les champs marqués d'une étoile (*) sont obligatoires.",
    "contact.form.validation.email": "Veuillez entrer une adresse email valide.",
    "contact.form.success": "Message envoyé avec succès !",
    "contact.form.error": "Erreur lors de l'envoi.",
    "contact.faq.title": "Questions Fréquentes",
    "contact.faq.q1": "Dans quelles zones intervenez-vous ?",
    "contact.faq.a1": "Nous intervenons sur l'ensemble du territoire marocain et à l'international pour des projets spécifiques.",
    "contact.faq.q2": "Quels sont vos délais pour un devis ?",
    "contact.info.hq": "Siège Social",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Appartement N°1, Mohammedia",
    "projects.hero.title": "Nos Réalisations",
    "projects.hero.subtitle": "Une expertise prouvée par des projets complexes et critiques.",
    "projects.tech.stack": "Technologies déployées",
    "projects.results": "Résultats obtenus",
    "projects.process.title": "Notre Processus d'Exécution",
    "projects.process.subtitle": "Une gestion de projet rigoureuse pour garantir qualité et délais.",
    "projects.process.step1": "Étude & Cahier des Charges",
    "projects.process.step2": "Conception & Développement",
    "projects.process.step3": "Câblage & Tests FAT",
    "projects.process.step4": "Mise en service & SAT",
    "projects.cta.title": "Un projet spécifique ?",
    "service.realisation.title": "Réalisation sur Site",
    "service.realisation.hero": "La maîtrise technique et la tenue des délais pour vos projets industriels.",
    "service.realisation.subtitle": "Excellence Opérationnelle sur le Terrain",
    "service.realisation.desc": "SOMATISME assure le montage et la mise en service de vos installations avec une rigueur absolue. Nos équipes interviennent pour garantir que chaque composant est installé selon les normes de sécurité et de performance les plus strictes.",
    "service.realisation.safety.title": "Sécurité & Conformité QHSE",
    "service.realisation.safety.desc": "La sécurité sur site est notre priorité. Nos techniciens disposent des habilitations nécessaires et respectent scrupuleusement les Plans de Prévention (PPSPS).",
    "service.realisation.safety.item1": "Habilitations électriques (B1V, B2V, BR, BC)",
    "service.realisation.domains.title": "Domaines d'Intervention",
    "service.realisation.cta.title": "Un projet de mise en service ?",
    "service.realisation.cta.btn": "Démarrer votre projet",
    "contact.form.phone": "Téléphone",
    "contact.form.company": "Entreprise",
    "contact.form.subject": "Sujet *",
    "contact.form.subject.placeholder": "Sélectionnez un sujet",
    "contact.form.subject.automation": "Automatisme Industriel",
    "contact.form.subject.regulation": "Régulation & Instrumentation",
    "contact.form.subject.electrical": "Installation Électrique",
    "contact.form.subject.maintenance": "Maintenance Industrielle",
    "contact.form.subject.other": "Autre demande",
    "contact.form.message": "Message *",
    "contact.form.message.placeholder": "Décrivez votre projet...",
    "contact.form.submit": "Envoyer le message",
    "contact.form.submitting": "Envoi en cours...",
    "contact.form.success": "Message envoyé avec succès ! Nous vous recontacterons bientôt.",
    "contact.form.error": "Erreur lors de l'envoi du message. Veuillez réessayer.",
    "contact.faq.q3": "Quelles marques d'automates supportez-vous ?",
    "contact.faq.a3": "Nous sommes experts sur Siemens (S7, TIA Portal), Schneider (M580, M340), Rockwell et Omron.",
    "contact.faq.q4": "Proposez-vous des contrats de maintenance ?",
    "contact.faq.a4": "Oui, nous proposons des contrats de maintenance préventive et curative sur mesure, adaptés à votre parc machine."
  },
  en: {
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.contact": "Contact",
    "home.hero.badge": "Industrial Expertise",
    "home.hero.title": "Automation Solutions",
    "home.hero.title.accent": " Premium",
    "home.hero.desc": "SOMATISME offers industrial automation, regulation, electrical installation, and maintenance solutions for modern B2B companies.",
    "home.hero.cta.quote": "Request a Quote",
    "home.hero.cta.discover": "Discover our services",
    "home.process.title": "Our Methodology",
    "home.process.subtitle": "Rigorous support from design to maintenance.",
    "home.why.title": "Why SOMATISME?",
    "home.why.subtitle": "Technical excellence at the service of your productivity.",
    "home.why.item1": "Multi-brand Expertise (Siemens, Schneider)",
    "home.why.item2": "Guaranteed Responsiveness: 24h/48h Intervention",
    "home.why.item3": "Total compliance with industrial standards (NFC, IEC)",
    "home.why.item4": "Mastery of Industry 4.0 technologies",
    "home.process.step1.title": "Audit & Analysis",
    "home.process.step1.desc": "In-depth study of your technical needs and production constraints.",
    "about.hero.title": "About SOMATISME",
    "about.hero.subtitle": "Leader in industrial automation solutions for over 15 years",
    "about.sectors.title": "Highly Diversified Sectors",
    "about.sectors.subtitle": "Cross-disciplinary expertise serving the industry.",
    "about.infra.title": "Infrastructure & Technical Means",
    "about.infra.subtitle": "A workspace designed for industrial excellence.",
    "about.infra.be.title": "Engineering Office",
    "about.infra.be.desc": "Advanced engineering equipped with the latest CAD software (EPLAN, AutoCAD). We conduct selectivity studies, power balances, and software development on dedicated simulation platforms.",
    "about.infra.atelier.title": "Assembly Workshop",
    "about.infra.atelier.desc": "Specialized workshop in Mohammedia for the production of control panels, consoles, and high-power switchboards. Every achievement undergoes rigorous continuity tests and FAT (Factory Acceptance Test) protocols.",
    "about.growth.title": "Steady and Controlled Growth",
    "about.growth.desc": "Since its creation, SOMATISME has maintained an upward trajectory by continuously investing in human capital and cutting-edge technological tools.",
    "about.finance.title": "A Particularly Healthy Balance Sheet",
    "about.finance.desc": "The strength of our financial structure allows us to confidently tackle large-scale projects. We guarantee our partners total longevity in our commitments.",
    "about.culture.title": "And above all… A Corporate Culture",
    "about.culture.subtitle": "For shared satisfaction and a trusting, long-term relationship with our clients.",
    "about.culture.passion.title": "Passion",
    "about.culture.passion.desc": "Industrial Automation and Real-Time Techniques.",
    "about.culture.innovation.title": "Innovation",
    "about.culture.innovation.desc": "Constant Research and Innovation.",
    "about.culture.service.title": "Service",
    "about.culture.service.desc": "Tailored Service and Availability.",
    "about.culture.integrity.title": "Integrity",
    "about.culture.integrity.desc": "Integrity and Independence of Mind.",
    "about.partners.title": "Our Partners",
    "about.partners.subtitle": "They trust us to master their processes.",
    "cta.contact": "Contact Us",
    "cta.ready": "Ready to work with us?",
    "sector.agro": "Agro-food",
    "sector.auto": "Automotive",
    "sector.chimie": "Chemical",
    "sector.ciment": "Cement & Quarries",
    "sector.medical": "Medical",
    "sector.metallurgie": "Metallurgy",
    "sector.micro": "Microelectronics",
    "sector.pharmacie": "Pharmacy",
    "sector.plasturgie": "Plastics",
    "sector.energie": "Energy Production",
    "sector.siderurgie": "Steel Industry",
    "sector.sante": "Health",
    "sector.eau": "Water Treatment",
    "services.hero.title": "Our Services",
    "services.hero.subtitle": "Comprehensive engineering solutions for operational excellence.",
    "services.nav.title": "Quick Navigation",
    "services.nav.desc": "Click on a service to access it or leave the area to read the details.",
    "services.quality.title": "Quality & Safety Commitment",
    "services.quality.desc": "Technical rigor is at the heart of every intervention.",
    "services.quality.item1": "Strict compliance with NFC 15-100 and IEC 61131-3 standards.",
    "services.quality.item2": "Systematic FAT (Factory Acceptance Test) in the workshop.",
    "services.quality.item3": "Documented SAT (Site Acceptance Test) commissioning protocols.",
    "services.quality.item4": "Electrical authorizations and machine safety (Directive 2006/42/EC).",
    "services.cta.title": "Need a custom solution?",
    "services.standards.title": "Standards & Compliance",
    "services.standards.desc": "All our achievements comply with strict international standards: NFC 15-100, IEC 61131, and machinery directives 2006/42/EC.",
    "services.brands.title": "System Expertise",
    "services.cta.desc": "Contact our experts to discuss your specific needs",
    "services.more": "Learn more",
    "service.conseil.title": "Consulting & Engineering",
    "service.automation.title": "Industrial Automation",
    "service.electrical.title": "Electrical Installation",
    "service.maintenance.title": "Technical Assistance",
    "service.formation.title": "Training",
    "service.realisation.title": "On-Site Realization",
    "service.realisation.hero": "Technical mastery and adherence to deadlines for your industrial projects.",
    "service.realisation.domains.title": "Fields of Intervention",
    "service.conseil.feature1.title": "Decision Support",
    "service.conseil.feature1.desc": "Comparative analysis and technical evaluations to secure your investments.",
    "service.conseil.feature2.title": "Innovation",
    "service.conseil.feature2.desc": "Search for breakthrough technical solutions to boost your productivity.",
    "service.conseil.feature3.title": "Compliance",
    "service.conseil.feature3.desc": "Writing specifications (APD/APS) aligned with industrial standards.",
    "service.conseil.item1": "Expertise and Diagnostics",
    "service.conseil.item2": "Technical feasibility studies",
    "service.conseil.cta": "Need an in-depth technical diagnostic?",
    "service.conseil.btn": "Request an expertise",
    "contact.hero.title": "Contact Us",
    "contact.hero.subtitle": "Tell us about your project. Our experts are ready to help.",
    "contact.info.title": "Contact Information",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.address": "Address",
    "contact.info.hq": "Headquarters",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Apartment N°1, Mohammedia",
    "contact.form.name": "Full Name *",
    "contact.form.email": "Email *",
    "contact.form.submit": "Send message",
    "contact.form.submitting": "Sending...",
    "contact.form.success": "Message sent successfully!",
    "contact.form.error": "Error during sending.",
    "contact.faq.title": "Frequently Asked Questions",
    "contact.faq.q1": "In which areas do you operate?",
    "contact.faq.a1": "We operate throughout Morocco and internationally for specific projects.",
    "contact.faq.q2": "What are your lead times for a quote?",
    "contact.info.hq": "Headquarters",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Apartment N°1, Mohammedia",
    "projects.hero.title": "Our Achievements",
    "projects.hero.subtitle": "Expertise proven by complex and critical projects.",
    "projects.tech.stack": "Deployed Technologies",
    "projects.results": "Obtained Results",
    "projects.process.title": "Our Execution Process",
    "projects.process.subtitle": "Rigorous project management to ensure quality and deadlines.",
    "projects.process.step1": "Study & Specifications",
    "projects.process.step2": "Design & Development",
    "projects.process.step3": "Wiring & FAT Testing",
    "projects.process.step4": "Commissioning & SAT",
    "projects.cta.title": "A specific project?",
    "service.realisation.title": "On-Site Realization",
    "service.realisation.hero": "Technical mastery and adherence to deadlines for your industrial projects.",
    "service.realisation.subtitle": "Operational Excellence in the Field",
    "service.realisation.desc": "SOMATISME ensures the assembly and commissioning of your installations with absolute rigor. Our teams intervene to ensure that every component is installed according to the strictest safety and performance standards.",
    "service.realisation.safety.title": "QHSE Safety & Compliance",
    "service.realisation.safety.desc": "Site safety is our priority. Our technicians have the necessary authorizations and scrupulously respect the Prevention Plans (PPSPS).",
    "service.realisation.safety.item1": "Electrical authorizations (B1V, B2V, BR, BC)",
    "service.realisation.domains.title": "Fields of Intervention",
    "service.realisation.cta.title": "A commissioning project?",
    "service.realisation.cta.btn": "Start your project",
    "contact.form.phone": "Phone",
    "contact.form.company": "Company",
    "contact.form.subject": "Subject *",
    "contact.form.subject.placeholder": "Select a subject",
    "contact.form.subject.automation": "Industrial Automation",
    "contact.form.subject.regulation": "Regulation & Instrumentation",
    "contact.form.subject.electrical": "Electrical Installation",
    "contact.form.subject.maintenance": "Industrial Maintenance",
    "contact.form.subject.other": "Other request",
    "contact.form.message": "Message *",
    "contact.form.message.placeholder": "Describe your project...",
    "contact.form.submit": "Send Message",
    "contact.form.submitting": "Sending...",
    "contact.form.success": "Message sent successfully! We will get back to you soon.",
    "contact.form.error": "Error sending message. Please try again.",
    "contact.faq.q3": "Which PLC brands do you support?",
    "contact.faq.a3": "We are experts in Siemens (S7, TIA Portal), Schneider (M580, M340), Rockwell, and Omron.",
    "contact.faq.q4": "Do you offer maintenance contracts?",
    "contact.faq.a4": "Yes, we offer tailored preventive and curative maintenance contracts, adapted to your machine fleet."
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Sobre Nosotros",
    "nav.services": "Servicios",
    "nav.projects": "Proyectos",
    "nav.contact": "Contacto",
    "home.hero.badge": "Experiencia Industrial",
    "home.hero.title": "Soluciones de Automatización",
    "home.hero.title.accent": " Premium",
    "home.hero.desc": "SOMATISME ofrece soluciones de automatización industrial, regulación, instalación eléctrica y mantenimiento para empresas B2B modernas.",
    "home.hero.cta.quote": "Solicitar Presupuesto",
    "home.hero.cta.discover": "Descubrir servicios",
    "home.process.title": "Nuestra Metodología",
    "home.process.subtitle": "Acompañamiento riguroso desde el diseño hasta el mantenimiento.",
    "home.why.title": "¿Por qué SOMATISME?",
    "home.why.subtitle": "Excelencia técnica al servicio de su productividad.",
    "home.why.item1": "Experiencia Multimarca (Siemens, Schneider)",
    "home.why.item2": "Reactividad garantizada: Intervención en 24h/48h",
    "home.why.item3": "Cumplimiento total con las normas industriales (NFC, IEC)",
    "home.why.item4": "Dominio de las tecnologías Industria 4.0",
    "home.process.step1.title": "Auditoría y Análisis",
    "home.process.step1.desc": "Estudio profundo de sus necesidades técnicas y limitaciones de producción.",
    "home.process.step2.title": "Diseño",
    "home.process.step2.desc": "Definición de arquitectura de software y hardware optimizada.",
    "home.process.step3.title": "Despliegue",
    "home.process.step3.desc": "Instalación en sitio, programación y pruebas rigurosas.",
    "home.process.step4.title": "Mantenimiento",
    "home.process.step4.desc": "Seguimiento post-proyecto, asistencia 24/7 y optimización.",
    "home.expertise.title": "Nuestras Áreas de Experiencia",
    "home.expertise.subtitle": "Soluciones integrales para todas sus necesidades industriales.",
    "about.hero.title": "Sobre SOMATISME",
    "about.hero.subtitle": "Líder en soluciones industriales por más de 15 años",
    "about.sectors.title": "Sectores Diversificados",
    "about.sectors.subtitle": "Experiencia transversal al servicio de la industria.",
    "about.infra.title": "Infraestructura y Medios Técnicos",
    "about.infra.subtitle": "Un entorno de trabajo diseñado para la excelencia industrial.",
    "about.infra.be.title": "Oficina de Proyectos",
    "about.infra.be.desc": "Ingeniería avanzada con software CAD/DAO (EPLAN, AutoCAD). Estudios de selectividad.",
    "about.infra.atelier.title": "Taller de Montaje",
    "about.infra.atelier.desc": "Taller especializado en Mohammedia para armarios y TGBT. Pruebas FAT rigurosas.",
    "about.growth.title": "Crecimiento Controlado",
    "about.growth.desc": "SOMATISME mantiene una trayectoria ascendente invirtiendo en capital humano y tecnología.",
    "about.finance.title": "Balance Saneado",
    "about.finance.desc": "La solidez de nuestra estructura financiera garantiza la perennidad de nuestros compromisos.",
    "about.culture.title": "Cultura de Empresa",
    "about.culture.subtitle": "Satisfacción compartida y relación de confianza duradera con nuestros clientes.",
    "about.partners.title": "Nuestros Socios",
    "about.partners.subtitle": "Confían en nosotros para el control de sus procesos.",
    "cta.contact": "Contáctenos",
    "cta.ready": "¿Listo para colaborar?",
    "services.hero.title": "Nuestros Servicios",
    "services.hero.subtitle": "Soluciones integrales de ingeniería para la excelencia operativa.",
    "services.quality.title": "Compromiso de Calidad",
    "services.quality.desc": "El rigor técnico en el corazón de cada intervención.",
    "services.quality.item1": "Cumplimiento estricto de normas NFC e IEC.",
    "services.quality.item2": "Pruebas FAT sistemáticas en taller.",
    "services.quality.item3": "Protocolos de puesta en marcha SAT.",
    "services.quality.item4": "Seguridad de máquinas (2006/42/CE).",
    "services.cta.title": "¿Necesita una solución a medida?",
    "services.more": "Saber más",
    "service.conseil.title": "Consultoría",
    "service.automation.title": "Automatización Industrial",
    "service.electrical.title": "Instalación Eléctrica",
    "service.maintenance.title": "Asistencia Técnica",
    "service.formation.title": "Formación",
    "service.realisation.title": "Realización en Sitio",
    "service.realisation.hero": "Dominio técnico y cumplimiento de plazos en sitio.",
    "service.realisation.domains.title": "Dominios",
    "service.realisation.cta.title": "¿Proyecto de puesta en marcha?",
    "service.realisation.cta.btn": "Iniciar proyecto",
    "contact.hero.title": "Contacto",
    "contact.hero.subtitle": "Háblenos de su proyecto. Estamos listos para ayudarle.",
    "contact.info.title": "Información de Contacto",
    "contact.info.phone": "Teléfono",
    "contact.info.email": "Email",
    "contact.info.address": "Dirección",
    "contact.info.hq": "Sede Social",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Apartamento N°1, Mohammedia",
    "contact.form.name": "Nombre completo *",
    "contact.form.email": "Email *",
    "contact.form.submit": "Enviar mensaje",
    "contact.form.submitting": "Enviando...",
    "contact.form.success": "¡Mensaje enviado con éxito!",
    "contact.form.error": "Error al enviar el mensaje.",
    "contact.faq.title": "Preguntas Frecuentes",
    "contact.faq.q1": "¿En qué zonas intervienen?",
    "contact.faq.a1": "Intervenimos en todo el territorio marroquí e internacionalmente.",
    "contact.faq.q2": "¿Plazos para presupuesto?",
    "contact.faq.q3": "¿Qué marcas de PLC soportan?",
    "contact.faq.a3": "Somos expertos en Siemens (S7, TIA Portal), Schneider (M580, M340) y Rockwell.",
    "contact.faq.q4": "¿Ofrecen contratos de mantenimiento?",
    "contact.faq.a4": "Sí, ofrecemos contratos de mantenimiento preventivo y correctivo a medida.",
    "projects.hero.title": "Realizaciones",
    "projects.hero.subtitle": "Experiencia probada en proyectos críticos y complejos.",
    "projects.process.title": "Nuestro Proceso",
    "projects.process.subtitle": "Gestión rigurosa de proyectos industriales.",
    "projects.process.step1": "Estudio y Pliego",
    "projects.process.step2": "Diseño y Desarrollo",
    "projects.process.step3": "Cableado y FAT",
    "projects.process.step4": "Puesta en marcha"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const isRTL = false;

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};