import React, { createContext, useContext } from 'react';

interface LanguageContextType {
  t: (key: string) => string;
}

const translations = {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.projects": "Projets",
    "nav.products": "Produits",
    "nav.contact": "Contact",
    "header.tagline": "Solutions d'automatisme industriel depuis plus de 15 ans",
    "home.hero.badge": "Expertise Industrielle",
    "home.hero.title": "Solutions d'Automatisme",
    "home.hero.title.accent": " Premium",
    "home.hero.desc": "SOMATISME propose des solutions d'automatisme industriel, régulation, installation électrique et maintenance pour les entreprises B2B modernes. Plus de 15 ans d'expérience pour transformer vos défis industriels en opportunités de croissance.",
    "home.hero.cta.quote": "Demander un devis",
    "home.hero.cta.discover": "Découvrir nos services",
    "home.hero.stats.projects": "50+ Projets réalisés",
    "home.hero.stats.experience": "15+ Années d'expérience",
    "home.hero.stats.satisfaction": "100% Clients satisfaits",
    "home.hero.card.title": "Technologie de Pointe",
    "home.hero.card.desc": "Systèmes d'automatisme dernière génération avec intégration IoT et maintenance prédictive pour une industrie intelligente.",
    "home.process.title": "Notre Méthodologie",
    "home.process.subtitle": "Un accompagnement rigoureux de la conception à la maintenance.",
    "home.why.title": "Pourquoi SOMATISME ?",
    "home.why.subtitle": "L'excellence technique au service de votre productivité. Un partenaire fiable pour transformer vos défis industriels en opportunités de croissance.",
    "home.why.item1": "Expertise Multimarque (Siemens, Schneider, Rockwell) - Plus de 15 ans d'expérience sur les principales plateformes d'automatisation industrielles.",
    "home.why.item2": "Réactivité garantie : Intervention sous 24h/48h - Notre équipe d'experts est disponible pour répondre rapidement à vos besoins urgents et assurer la continuité de vos opérations.",
    "home.why.item3": "Conformité totale aux normes industrielles (NFC 15-100, CEI 61131) - Toutes nos réalisations respectent les standards internationaux pour garantir sécurité et qualité.",
    "home.why.item4": "Maîtrise des technologies Industrie 4.0 - Intégration avancée de l'IoT, de la maintenance prédictive et des systèmes connectés pour des usines intelligentes.",
    "home.why.item5": "Accompagnement personnalisé - Un interlocuteur unique dédié à votre projet, de l'étude à la mise en service et au-delà.",
    "home.expertise.title": "Nos Domaines d'Expertise",
    "home.expertise.subtitle": "Des solutions techniques complètes pour tous vos besoins industriels",
    "home.expertise.automation.title": "Automatisme Industriel",
    "home.expertise.automation.desc": "Systèmes de contrôle et d'automatisation avancés pour optimiser vos processus de production. Nous développons des solutions sur mesure avec des automates programmables (PLC), systèmes SCADA, et interfaces homme-machine (IHM) pour garantir une performance optimale et une traçabilité complète de vos opérations.",
    "home.expertise.regulation.title": "Régulation & Instrumentation",
    "home.expertise.regulation.desc": "Solutions de mesure et contrôle de précision pour assurer la qualité et la stabilité de vos processus industriels. Nous installons et configurons des boucles de régulation, capteurs, transmetteurs et instruments de mesure pour une maîtrise totale de vos paramètres critiques.",
    "home.expertise.electrical.title": "Installation Électrique",
    "home.expertise.electrical.desc": "Solutions électriques sécurisées et conformes aux normes pour garantir la fiabilité et la sécurité de vos installations. Nos équipes réalisent des études, câblages, mises en service et certifications électriques selon les normes NFC 15-100 et directives européennes.",
    "home.expertise.maintenance.title": "Maintenance Industrielle",
    "home.expertise.maintenance.desc": "Support technique complet et maintenance préventive pour assurer la continuité de vos opérations et maximiser la durée de vie de vos équipements. Nous proposons des contrats de maintenance sur mesure, interventions d'urgence 24/7, et optimisation de vos systèmes existants.",
    "home.process.step1.title": "Audit & Analyse",
    "home.process.step1.desc": "Étude approfondie de vos besoins techniques et contraintes de production. Nos experts analysent vos installations existantes, identifient les axes d'amélioration et élaborent un diagnostic précis pour définir les solutions adaptées à vos objectifs.",
    "home.process.step2.title": "Conception",
    "home.process.step2.desc": "Définition de l'architecture logicielle et matérielle optimisée. Nous concevons des solutions sur mesure en sélectionnant les technologies les plus appropriées (PLC, SCADA, IHM) pour garantir performance, évolutivité et conformité aux normes industrielles.",
    "home.process.step3.title": "Déploiement",
    "home.process.step3.desc": "Installation sur site, programmation et tests rigoureux. Nos équipes interviennent sur votre site pour l'assemblage, le câblage, la programmation et les tests FAT (Factory Acceptance Test) selon les standards les plus exigeants.",
    "home.process.step4.title": "Maintenance",
    "home.process.step4.desc": "Suivi post-projet, assistance 24/7 et optimisation continue. Nous assurons un accompagnement durable avec des contrats de maintenance, support technique réactif et mises à jour régulières pour maximiser la durée de vie de vos installations.",
    "about.hero.title": "À propos de SOMATISME",
    "about.hero.subtitle": "Leader en solutions d'automatisme industriel depuis plus de 15 ans. Notre mission est de fournir des solutions techniques innovantes pour optimiser vos processus industriels et garantir votre compétitivité.",
    "about.sectors.title": "Des secteurs d'activité très diversifiés",
    "about.sectors.subtitle": "Une expertise transversale au service de l'industrie. Nous intervenons dans de multiples secteurs pour apporter notre savoir-faire technique et notre capacité d'adaptation à chaque contexte industriel spécifique.",
    "about.infra.title": "Infrastructure & Moyens Techniques",
    "about.infra.subtitle": "Un environnement de travail conçu pour l'excellence industrielle.",
    "about.infra.be.title": "Bureau d'Études",
    "about.infra.be.desc": "Ingénierie avancée équipée des derniers logiciels de CAO/DAO (EPLAN, AutoCAD). Nous réalisons des études de sélectivité, des bilans de puissance et le développement software sur des plateformes de simulation dédiées.",
    "about.infra.atelier.title": "Atelier de Montage",
    "about.infra.atelier.desc": "Atelier spécialisé de Mohammedia pour la réalisation d'armoires, pupitres et TGBT de forte puissance. Chaque réalisation subit des tests de continuité et des protocoles FAT (Factory Acceptance Test) rigoureux.",
    "about.growth.title": "Une croissance régulière et maîtrisée",
    "about.growth.desc": "Depuis sa création, SOMATISME a su maintenir une trajectoire ascendante en investissant continuellement dans le capital humain et les outils technologiques de pointe. Notre stratégie de développement durable nous permet d'accompagner nos clients sur le long terme avec une vision claire de l'avenir industriel.",
    "about.finance.title": "Un bilan particulièrement sain",
    "about.finance.desc": "La solidité de notre structure financière nous permet d'aborder sereinement des projets de grande envergure. Nous garantissons à nos partenaires une pérennité totale dans nos engagements, avec une gestion rigoureuse et transparente de nos ressources.",
    "about.culture.title": "Et surtout … Une culture d'entreprise",
    "about.culture.subtitle": "Pour une satisfaction partagée et une relation confiante et pérenne avec nos clients.",
    "about.culture.passion.title": "Passion",
    "about.culture.passion.desc": "L'Automatisme industriel et les Techniques du temps réel. Notre équipe est animée par une véritable passion pour l'innovation technique et l'excellence opérationnelle.",
    "about.culture.innovation.title": "Innovation",
    "about.culture.innovation.desc": "Recherche et Innovation constante. Nous investissons continuellement dans les nouvelles technologies pour rester à l'avant-garde de notre domaine.",
    "about.culture.service.title": "Service",
    "about.culture.service.desc": "Service et Disponibilité sur-mesure. Notre engagement est de fournir un accompagnement personnalisé adapté aux besoins spécifiques de chaque client.",
    "about.culture.integrity.title": "Intégrité",
    "about.culture.integrity.desc": "Intégrité et Indépendance d'esprit. Nous agissons avec transparence et éthique dans toutes nos relations professionnelles.",
    "about.stats.years": "15+ Années d'expérience",
    "about.stats.projects": "50+ Projets réalisés",
    "about.stats.satisfaction": "100% Clients satisfaits",
    "about.stats.support": "24/7 Support technique",
    "about.partners.title": "Nos Partenaires",
    "about.partners.subtitle": "Ils nous font confiance pour la maîtrise de leurs procédés.",
    "cta.contact": "Nous contacter",
    "cta.ready": "Prêt à collaborer avec nous ?",
    "cta.home.title": "Prêt à transformer votre industrie ?",
    "cta.home.subtitle": "Contactez nos experts pour discuter de vos besoins spécifiques et découvrir comment nos solutions peuvent optimiser vos processus industriels.",
    "cta.home.button": "Nous contacter maintenant",
    "footer.tagline": "Solutions d'automatisme industriel, régulation et installation électrique pour l'industrie.",
    "footer.phone": "+212 679 825 646",
    "footer.fax": "",
    "footer.email": "info@somatisme.ma",
    "footer.address": "Rue résistance residence Nassime GH 12 Appt N°1, Mohammedia",
    "footer.copyright": "© 2026 SOMATISME. Tous droits réservés.",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "sector.agro": "Agro-alimentaire",
    "sector.auto": "Automobile",
    "sector.chimie": "Chimie",
    "sector.ciment": "Cimenteries et Carrières",
    "sector.medical": "Médical",
    "sector.metallurgie": "Métallurgie",
    "sector.micro": "Micro-électronique",
    "sector.pharmacie": "Pharmacie",
    "sector.plasturgie": "Plasturgie",
    "sector.energie": "Production d’énergie",
    "sector.siderurgie": "Sidérurgie",
    "sector.sante": "Santé",
    "sector.eau": "Traitement de l’eau",
    "services.hero.title": "Nos Services",
    "services.hero.subtitle": "Solutions d'ingénierie complètes pour l'excellence opérationnelle. Notre approche intégrée couvre tous les aspects de vos besoins industriels, de la conception à la maintenance.",
    "services.conseil.title": "Conseil & Ingénierie",
    "services.conseil.desc": "Expertise opérationnelle, tout au long de la vie de votre installation. Nos experts vous accompagnent à chaque étape pour optimiser vos processus et garantir la performance de vos équipements.",
    "services.conseil.item1": "Expertises et diagnostics d'obsolescence (Audit de parc)",
    "services.conseil.item2": "Études de faisabilité technique et Industrie 4.0",
    "services.conseil.item3": "Optimisation énergétique et rendement (OEE/TRS)",
    "services.conseil.item4": "Définition d'architectures (Centralisé, Distribué, Cloud)",
    "services.conseil.item5": "Analyses fonctionnelles détaillées et spécifications",
    "services.conseil.item6": "Rédaction d'APS, APD et cahiers des charges fonctionnels",
    "services.conseil.item7": "Audit de cybersécurité des réseaux industriels",
    "services.automation.title": "Automatisme Industriel",
    "services.automation.desc": "De l'automate programmable aux systèmes automatisés les plus complexes et réseaux élaborés. Nous maîtrisons les technologies de pointe pour créer des solutions sur mesure adaptées à vos besoins.",
    "services.automation.item1": "Automates : Siemens (S7-1200/1500), Schneider (M580/M340), Rockwell",
    "services.automation.item2": "Migration de systèmes (Retrofit S5 vers S7, TSX vers M580)",
    "services.automation.item3": "Systèmes SCADA complexes (WinCC, Ignition, PCVue)",
    "services.automation.item4": "Régulation de process et boucles PID complexes",
    "services.automation.item5": "Réseaux industriels (Profinet, EtherNet/IP, Modbus TCP)",
    "services.automation.item6": "Interfaçage HMI ergonomique et gestion de Batch",
    "services.electrical.title": "Installation Électrique",
    "services.electrical.desc": "Parce que l'automation en a aussi besoin... SOMATISME met son énergie à votre disposition. Nos équipes qualifiées assurent des installations conformes et sécurisées.",
    "services.electrical.item1": "Conception et réalisation de TGBT et tableaux de distribution",
    "services.electrical.item2": "Câblage d'armoires de commande et relayage en atelier",
    "services.electrical.item3": "Installation de variateurs de puissance jusqu'à 330KW",
    "services.electrical.item4": "Analyse de la qualité d'énergie (harmoniques, facteur de puissance)",
    "services.electrical.item5": "Mise en conformité selon les normes NFC 15-100",
    "services.electrical.item6": "Audit thermographique et diagnostic d'installations",
    "services.site.title": "Réalisation sur Site",
    "services.site.desc": "Montage et mise en service sur site : La maîtrise technique et la tenue des délais. Nos équipes garantissent une intervention professionnelle et respectueuse de vos contraintes.",
    "services.site.item1": "Supervision technique de montage et coordination (PPSPS)",
    "services.site.item2": "Installation d'équipements : cheminements et raccordements",
    "services.site.item3": "Tests de continuité et vérification du câblage I/O",
    "services.site.item4": "Mise en service industrielle et validation des performances (SAT)",
    "services.site.item5": "Assistance au démarrage et remise du dossier (DOE)",
    "services.assistance.title": "Assistance Technique",
    "services.assistance.desc": "Assistance technique disponible : La sérénité de vos opérateurs et la disponibilité de vos installations. Notre support réactif assure la continuité de vos opérations.",
    "services.assistance.item1": "Intervention corrective d'urgence sur site (24h/48h)",
    "services.assistance.item2": "Télédiagnostic et assistance à distance (VPN sécurisé)",
    "services.assistance.item3": "Maintenance préventive personnalisée et curative",
    "services.assistance.item4": "Mise à jour (Upgrade) software automates et SCADA",
    "services.assistance.item5": "Dépannage d'urgence sur variateurs et servomoteurs",
    "services.assistance.item6": "Audit de disponibilité et gestion de l'obsolescence",
    "services.training.title": "Formation",
    "services.training.desc": "Formations à la carte, pratiques et efficaces par des hommes de terrain expérimentés. Nous partageons notre expertise pour renforcer les compétences de vos équipes.",
    "services.training.item1": "Diagnostic de pannes sur systèmes automatisés (Niveau 1 & 2)",
    "services.training.item2": "Programmation d'automates (LADDER, SCL, GRAFCET)",
    "services.training.item3": "Maintenance et exploitation de systèmes SCADA / HMI",
    "services.training.item4": "Formation sur équipements spécifiques (Siemens, Schneider, etc.)",
    "services.quality.title": "Engagement Qualité & Sécurité",
    "services.quality.desc": "La rigueur technique est au cœur de chaque intervention. Nous appliquons les standards les plus élevés pour garantir la qualité et la sécurité de nos réalisations.",
    "services.quality.item1": "Conformité stricte aux normes NFC 15-100 et CEI 61131-3.",
    "services.quality.item2": "Tests FAT (Factory Acceptance Test) systématiques en atelier.",
    "services.quality.item3": "Protocoles de mise en service SAT (Site Acceptance Test) documentés.",
    "services.quality.item4": "Habilitations électriques et sécurité machine (Directive 2006/42/CE).",
    "services.nav.title": "Navigation Rapide",
    "services.nav.desc": "Cliquez sur un service pour y accéder ou quittez la zone pour lire les détails.",
    "services.cta.title": "Besoin d'une solution personnalisée ?",
    "services.standards.title": "Normes & Standards",
    "services.standards.desc": "Toutes nos réalisations sont conformes aux normes internationales strictes : NFC 15-100, CEI 61131, et directives machines 2006/42/CE.",
    "services.brands.title": "Expertise Systèmes",
    "services.cta.desc": "Contactez nos experts pour discuter de vos besoins spécifiques",
    "services.more": "En savoir plus",
    "projects.hero.title": "Nos Réalisations",
    "projects.hero.subtitle": "Une expertise prouvée par des projets complexes et critiques. Découvrez comment nous avons transformé les défis industriels de nos clients en succès opérationnels.",
    "projects.textile.title": "Automatisation Usine Textile",
    "projects.textile.category": "Automatisme",
    "projects.textile.desc": "Ingénierie complète et programmation d'une ligne de production. Intégration de 40 variateurs de vitesse et synchronisation multi-axes pour optimiser la productivité.",
    "projects.textile.tech": "Siemens S7-1500, WinCC OA, Profinet",
    "projects.textile.result": "+25% de productivité, traçabilité totale",
    "projects.electrical.title": "Installation Électrique Complexe",
    "projects.electrical.category": "Installation Électrique",
    "projects.electrical.desc": "Conception et montage de TGBT 3200A. Étude de sélectivité et déploiement de canalisations préfabriquées pour unité de sidérurgie.",
    "projects.electrical.tech": "TGBT 2500A, Etude de sélectivité, Canalisations préfabriquées",
    "projects.electrical.result": "Conformité NFC 15-100, continuité de service assurée",
    "projects.regulation.title": "Système de Régulation Avancé",
    "projects.regulation.category": "Régulation",
    "projects.regulation.desc": "Instrumentation complète d'un réacteur chimique. Contrôle précis de température et pression avec boucles PID complexes pour garantir la qualité du produit.",
    "projects.regulation.tech": "Capteurs Endress+Hauser, Vannes de régulation, Boucles PID",
    "projects.regulation.result": "Précision de mesure < 0.1%, réduction pertes matières",
    "projects.maintenance.title": "Maintenance Préventive 24/7",
    "projects.maintenance.category": "Maintenance",
    "projects.maintenance.desc": "Contrat de maintenance globale multi-sites. Audit thermographique et analyse vibratoire périodique des moteurs critiques pour prévenir les pannes.",
    "projects.maintenance.tech": "Audit thermographique, Analyse vibratoire, Supervision SCADA",
    "projects.maintenance.result": "Réduction de 15% des arrêts non programmés",
    "projects.retrofit.title": "Retrofit Presse Hydraulique 500T",
    "projects.retrofit.category": "Modernisation",
    "projects.retrofit.desc": "Modernisation complète de la commande. Remplacement automate obsolète par architecture Fail-safe et HMI tactile pour améliorer la sécurité et la performance.",
    "projects.retrofit.tech": "Siemens S7-1500F, Safety I/O, Profisafe",
    "projects.retrofit.result": "Temps de cycle -18%, conformité sécurité machine",
    "projects.pumping.title": "Contrôle Commande Station Pompage",
    "projects.pumping.category": "Traitement Eau",
    "projects.pumping.desc": "Automatisation d'une station de traitement d'eau avec télégestion et remontée d'alarmes par réseau sans fil pour un monitoring continu.",
    "projects.pumping.tech": "Schneider M580, Radio/GPRS, Logiciel de supervision",
    "projects.pumping.result": "Optimisation énergétique de 20%, monitoring 24/7",
    "projects.process.title": "Notre Processus d'Exécution",
    "projects.process.subtitle": "Une gestion de projet rigoureuse pour garantir qualité et délais. Notre méthodologie éprouve assure le succès de chaque projet.",
    "projects.process.step1.title": "Étude & Cahier des Charges",
    "projects.process.step1.desc": "Analyse des besoins et rédaction des spécifications fonctionnelles (AF/AO). Nous définissons précisément vos exigences pour garantir une solution adaptée.",
    "projects.process.step2.title": "Conception & Développement",
    "projects.process.step2.desc": "Étude électrique, programmation PLC/HMI et conception des architectures réseaux. Nos experts développent des solutions optimisées et évolutives.",
    "projects.process.step3.title": "Câblage & Tests FAT",
    "projects.process.step3.desc": "Montage des armoires en atelier et tests de validation internes avant livraison. Chaque équipement subit des tests rigoureux selon les standards industriels.",
    "projects.process.step4.title": "Mise en service & SAT",
    "projects.process.step4.desc": "Installation sur site, essais d'ensemble et formation des opérateurs. Nous assurons une transition en douceur vers votre nouvelle installation.",
    "projects.cta.title": "Prêt à démarrer votre projet ?",
    "service.conseil.title": "Conseil & Ingénierie",
    "service.automation.title": "Automatisme Industriel",
    "service.electrical.title": "Installation Électrique",
    "service.maintenance.title": "Assistance Technique",
    "service.formation.title": "Formation",
    "service.realisation.title": "Réalisation sur Site",
    "service.realisation.hero": "La maîtrise technique et la tenue des délais pour vos projets industriels.",
    "service.realisation.domains.title": "Nos Domaines d'Intervention",
    "service.conseil.feature1.title": "Aide à la décision",
    "service.conseil.feature1.desc": "Analyses comparatives et évaluations techniques pour sécuriser vos investissements.",
    "service.conseil.feature2.title": "Innovation",
    "service.conseil.feature2.desc": "Recherche de solutions techniques en rupture pour booster votre productivité.",
    "service.conseil.feature3.title": "Conformité",
    "service.conseil.feature3.desc": "Rédaction de cahiers des charges (APD/APS) alignés sur les standards industriels.",
    "service.conseil.item1": "Expertises et Diagnostics",
    "service.conseil.item2": "Études de faisabilité technique",
    "service.conseil.cta": "Besoin d'un diagnostic technique approfondi ?",
    "service.conseil.btn": "Demander une expertise",
    "contact.hero.title": "Nous Contacter",
    "contact.hero.subtitle": "Parlez-nous de votre projet. Nos experts sont prêts à vous aider.",
    "contact.info.title": "Informations de Contact",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.address": "Adresse",
    "contact.info.hq": "Siège Social",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Appartement N°1, Mohammedia",
    "contact.form.name": "Nom complet *",
    "contact.form.email": "Email *",
    "contact.form.submit": "Envoyer le message",
    "contact.form.submitting": "Envoi en cours...",
    "contact.form.privacy": "Vos données sont traitées en toute confidentialité conformément à la politique de protection des données industrielles.",
    "contact.form.required": "Les champs marqués d'une étoile (*) sont obligatoires.",
    "contact.form.validation.email": "Veuillez entrer une adresse email valide.",
    "contact.form.validation.phone": "Veuillez entrer un numéro de téléphone valide (06xxxxxxxx ou +212...)",
    "contact.form.success": "Message envoyé avec succès !",
    "contact.form.error": "Erreur lors de l'envoi.",
    "contact.terms.title": "Conditions d'Utilisation",
    "contact.terms.description": "Veuillez accepter nos conditions d'utilisation avant de soumettre votre demande.",
    "contact.terms.accept": "J'accepte les conditions d'utilisation",
    "contact.terms.scroll": "Faites défiler jusqu'en bas pour activer le bouton",
    "contact.terms.submit": "Soumettre ma demande",
    "contact.faq.title": "Questions Fréquentes",
    "contact.faq.q1": "Dans quelles zones intervenez-vous ?",
    "contact.faq.a1": "Nous intervenons sur l'ensemble du territoire marocain et à l'international pour des projets spécifiques. Nos équipes sont basées à Mohammedia et peuvent se déployer rapidement sur tous les sites industriels du Maroc et des pays limitrophes selon vos besoins.",
    "contact.faq.q2": "Quelles marques d'automates supportez-vous ?",
    "contact.faq.a2": "Nous sommes experts sur les principales marques d'automatismes industriels : Siemens (S7, TIA Portal), Schneider (M580, M340), Rockwell et Omron. Notre expertise multimarque nous permet de travailler avec vos équipements existants ou de vous conseiller sur les meilleures solutions pour vos nouveaux projets.",
    "contact.faq.q3": "Proposez-vous des contrats de maintenance ?",
    "contact.faq.a3": "Oui, nous proposons des contrats de maintenance préventive et curative sur mesure, adaptés à votre parc machine. Nos contrats incluent des visites régulières, des audits de performance, un support technique 24/7 et des interventions d'urgence pour assurer la continuité de vos opérations.",
    "contact.faq.q4": "Quels sont vos délais pour un devis ?",
    "contact.faq.a4": "Pour une demande standard, nous nous engageons à vous fournir un chiffrage détaillé sous 48h à 72h après réception du cahier des charges. Pour les projets d'urgence ou complexes, nous pouvons proposer une intervention rapide pour évaluer vos besoins sur site.",
    "projects.tech.stack": "Technologies déployées",
    "projects.results": "Résultats obtenus",
    "projects.process.step1": "Étude & Cahier des Charges",
    "projects.process.step2": "Conception & Développement",
    "projects.process.step3": "Câblage & Tests FAT",
    "projects.process.step4": "Mise en service & SAT",
    "service.realisation.subtitle": "Excellence Opérationnelle sur le Terrain",
    "service.realisation.desc": "SOMATISME assure le montage et la mise en service de vos installations avec une rigueur absolue. Nos équipes interviennent pour garantir que chaque composant est installé selon les normes de sécurité et de performance les plus strictes.",
    "service.realisation.safety.title": "Sécurité & Conformité QHSE",
    "service.realisation.safety.desc": "La sécurité sur site est notre priorité. Nos techniciens disposent des habilitations nécessaires et respectent scrupuleusement les Plans de Prévention (PPSPS).",
    "service.realisation.safety.item1": "Habilitations électriques (B1V, B2V, BR, BC)",
    "service.realisation.cta.title": "Un projet de mise en service ?",
    "service.realisation.cta.btn": "Démarrer votre projet",
    "contact.form.phone": "Téléphone",
    "contact.form.company": "Entreprise",
    "contact.form.subject": "Sujet *",
    "contact.form.subject.placeholder": "Sélectionnez un sujet",
    "contact.form.subject.automation": "Automatisme Industriel",
    "contact.form.subject.regulation": "Régulation & Instrumentation",
    "contact.form.subject.electrical": "Installation Électrique",
    "contact.form.subject.maintenance": "Maintenance Industrielle",
    "contact.form.subject.other": "Autre demande",
    "contact.form.message": "Message *",
    "contact.form.message.placeholder": "Décrivez votre projet...",
    "contact.form.name.placeholder": "Mohammed Benali",
    "contact.form.email.placeholder": "exemple@gmail.com",
    "contact.form.phone.placeholder": "06XXXXXXXX",
    "contact.form.company.placeholder": "Société ABC",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const t = (key: string) => {
    return (translations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};