import React, { createContext, useContext } from 'react';

interface LanguageContextType {
  t: (key: string) => string;
}

const translations = {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.projects": "Projets",
    "nav.contact": "Contact",
    "home.hero.badge": "Expertise Industrielle",
    "home.hero.title": "Solutions d'Automatisme",
    "home.hero.title.accent": " Premium",
    "home.hero.desc": "SOMATISME propose des solutions d'automatisme industriel, régulation, installation électrique et maintenance pour les entreprises B2B modernes.",
    "home.hero.cta.quote": "Demander un devis",
    "home.hero.cta.discover": "Découvrir nos services",
    "home.process.title": "Notre Méthodologie",
    "home.process.subtitle": "Un accompagnement rigoureux de la conception à la maintenance.",
    "home.why.title": "Pourquoi SOMATISME ?",
    "home.why.subtitle": "L'excellence technique au service de votre productivité.",
    "home.why.item1": "Expertise Multimarque (Siemens, Schneider)",
    "home.why.item2": "Réactivité garantie : Intervention sous 24h/48h",
    "home.why.item3": "Conformité totale aux normes industrielles (NFC, CEI)",
    "home.why.item4": "Maîtrise des technologies Industrie 4.0",
    "home.expertise.title": "Nos Domaines d'Expertise",
    "home.expertise.subtitle": "Des solutions techniques complètes pour tous vos besoins industriels",
    "home.process.step1.title": "Audit & Analyse",
    "home.process.step1.desc": "Étude approfondie de vos besoins techniques et contraintes de production.",
    "home.process.step2.title": "Conception",
    "home.process.step2.desc": "Définition de l'architecture logicielle et matérielle optimisée.",
    "home.process.step3.title": "Déploiement",
    "home.process.step3.desc": "Installation sur site, programmation et tests rigoureux.",
    "home.process.step4.title": "Maintenance",
    "home.process.step4.desc": "Suivi post-projet, assistance 24/7 et optimisation continue.",
    "about.hero.title": "À propos de SOMATISME",
    "about.hero.subtitle": "Leader en solutions d'automatisme industriel depuis plus de 15 ans",
    "about.sectors.title": "Des secteurs d'activité très diversifiés",
    "about.sectors.subtitle": "Une expertise transversale au service de l'industrie.",
    "about.infra.title": "Infrastructure & Moyens Techniques",
    "about.infra.subtitle": "Un environnement de travail conçu pour l'excellence industrielle.",
    "about.infra.be.title": "Bureau d'Études",
    "about.infra.be.desc": "Ingénierie avancée équipée des derniers logiciels de CAO/DAO (EPLAN, AutoCAD). Nous réalisons des études de sélectivité, des bilans de puissance et le développement software sur des plateformes de simulation dédiées.",
    "about.infra.atelier.title": "Atelier de Montage",
    "about.infra.atelier.desc": "Atelier spécialisé de Mohammedia pour la réalisation d'armoires, pupitres et TGBT de forte puissance. Chaque réalisation subit des tests de continuité et des protocoles FAT (Factory Acceptance Test) rigoureux.",
    "about.growth.title": "Une croissance régulière et maîtrisée",
    "about.growth.desc": "Depuis sa création, SOMATISME a su maintenir une trajectoire ascendante en investissant continuellement dans le capital humain et les outils technologiques de pointe.",
    "about.finance.title": "Un bilan particulièrement sain",
    "about.finance.desc": "La solidité de notre structure financière nous permet d'aborder sereinement des projets de grande envergure. Nous garantissons à nos partenaires une pérennité totale dans nos engagements.",
    "about.culture.title": "Et surtout … Une culture d’entreprise",
    "about.culture.subtitle": "Pour une satisfaction partagée et une relation confiante et pérenne avec nos clients.",
    "about.culture.passion.title": "Passion",
    "about.culture.passion.desc": "L’Automatisme industriel et les Techniques du temps réel.",
    "about.culture.innovation.title": "Innovation",
    "about.culture.innovation.desc": "Recherche et Innovation constante.",
    "about.culture.service.title": "Service",
    "about.culture.service.desc": "Service et Disponibilité sur-mesure.",
    "about.culture.integrity.title": "Intégrité",
    "about.culture.integrity.desc": "Intégrité et Indépendance d’esprit.",
    "about.partners.title": "Nos Partenaires",
    "about.partners.subtitle": "Ils nous font confiance pour la maîtrise de leurs procédés.",
    "cta.contact": "Nous contacter",
    "cta.ready": "Prêt à collaborer avec nous ?",
    "sector.agro": "Agro-alimentaire",
    "sector.auto": "Automobile",
    "sector.chimie": "Chimie",
    "sector.ciment": "Cimenteries et Carrières",
    "sector.medical": "Médical",
    "sector.metallurgie": "Métallurgie",
    "sector.micro": "Micro-électronique",
    "sector.pharmacie": "Pharmacie",
    "sector.plasturgie": "Plasturgie",
    "sector.energie": "Production d’énergie",
    "sector.siderurgie": "Sidérurgie",
    "sector.sante": "Santé",
    "sector.eau": "Traitement de l’eau",
    "services.hero.title": "Nos Services",
    "services.hero.subtitle": "Solutions d'ingénierie complètes pour l'excellence opérationnelle.",
    "services.nav.title": "Navigation Rapide",
    "services.nav.desc": "Cliquez sur un service pour y accéder ou quittez la zone pour lire les détails.",
    "services.quality.title": "Engagement Qualité & Sécurité",
    "services.quality.desc": "La rigueur technique est au cœur de chaque intervention.",
    "services.quality.item1": "Conformité stricte aux normes NFC 15-100 et CEI 61131-3.",
    "services.quality.item2": "Tests FAT (Factory Acceptance Test) systématiques en atelier.",
    "services.quality.item3": "Protocoles de mise en service SAT (Site Acceptance Test) documentés.",
    "services.quality.item4": "Habilitations électriques et sécurité machine (Directive 2006/42/CE).",
    "services.cta.title": "Besoin d'une solution personnalisée ?",
    "services.standards.title": "Normes & Standards",
    "services.standards.desc": "Toutes nos réalisations sont conformes aux normes internationales strictes : NFC 15-100, CEI 61131, et directives machines 2006/42/CE.",
    "services.brands.title": "Expertise Systèmes",
    "services.cta.desc": "Contactez nos experts pour discuter de vos besoins spécifiques",
    "services.more": "En savoir plus",
    "service.conseil.title": "Conseil & Ingénierie",
    "service.automation.title": "Automatisme Industriel",
    "service.electrical.title": "Installation Électrique",
    "service.maintenance.title": "Assistance Technique",
    "service.formation.title": "Formation",
    "service.realisation.title": "Réalisation sur Site",
    "service.realisation.hero": "La maîtrise technique et la tenue des délais pour vos projets industriels.",
    "service.conseil.feature1.title": "Aide à la décision",
    "service.conseil.feature1.desc": "Analyses comparatives et évaluations techniques pour sécuriser vos investissements.",
    "service.conseil.feature2.title": "Innovation",
    "service.conseil.feature2.desc": "Recherche de solutions techniques en rupture pour booster votre productivité.",
    "service.conseil.feature3.title": "Conformité",
    "service.conseil.feature3.desc": "Rédaction de cahiers des charges (APD/APS) alignés sur les standards industriels.",
    "service.conseil.item1": "Expertises et Diagnostics",
    "service.conseil.item2": "Études de faisabilité technique",
    "service.conseil.cta": "Besoin d'un diagnostic technique approfondi ?",
    "service.conseil.btn": "Demander une expertise",
    "contact.hero.title": "Nous Contacter",
    "contact.hero.subtitle": "Parlez-nous de votre projet. Nos experts sont prêts à vous aider.",
    "contact.info.title": "Informations de Contact",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.address": "Adresse",
    "contact.info.hq": "Siège Social",
    "contact.info.hq.address": "Rue résistance residence Nassime GH 12 Appartement N°1, Mohammedia",
    "contact.form.name": "Nom complet *",
    "contact.form.email": "Email *",
    "contact.form.submit": "Envoyer le message",
    "contact.form.submitting": "Envoi en cours...",
    "contact.form.privacy": "Vos données sont traitées en toute confidentialité conformément à la politique de protection des données industrielles.",
    "contact.form.required": "Les champs marqués d'une étoile (*) sont obligatoires.",
    "contact.form.validation.email": "Veuillez entrer une adresse email valide.",
    "contact.form.success": "Message envoyé avec succès !",
    "contact.form.error": "Erreur lors de l'envoi.",
    "contact.faq.title": "Questions Fréquentes",
    "contact.faq.q1": "Dans quelles zones intervenez-vous ?",
    "contact.faq.a1": "Nous intervenons sur l'ensemble du territoire marocain et à l'international pour des projets spécifiques.",
    "contact.faq.q2": "Quels sont vos délais pour un devis ?",
    "contact.faq.a2": "Pour une demande standard, nous nous engageons à vous fournir un chiffrage détaillé sous 48h à 72h après réception du cahier des charges.",
    "projects.hero.title": "Nos Réalisations",
    "projects.hero.subtitle": "Une expertise prouvée par des projets complexes et critiques.",
    "projects.tech.stack": "Technologies déployées",
    "projects.results": "Résultats obtenus",
    "projects.process.title": "Notre Processus d'Exécution",
    "projects.process.subtitle": "Une gestion de projet rigoureuse pour garantir qualité et délais.",
    "projects.process.step1": "Étude & Cahier des Charges",
    "projects.process.step2": "Conception & Développement",
    "projects.process.step3": "Câblage & Tests FAT",
    "projects.process.step4": "Mise en service & SAT",
    "projects.cta.title": "Un projet spécifique ?",
    "service.realisation.subtitle": "Excellence Opérationnelle sur le Terrain",
    "service.realisation.desc": "SOMATISME assure le montage et la mise en service de vos installations avec une rigueur absolue. Nos équipes interviennent pour garantir que chaque composant est installé selon les normes de sécurité et de performance les plus strictes.",
    "service.realisation.safety.title": "Sécurité & Conformité QHSE",
    "service.realisation.safety.desc": "La sécurité sur site est notre priorité. Nos techniciens disposent des habilitations nécessaires et respectent scrupuleusement les Plans de Prévention (PPSPS).",
    "service.realisation.safety.item1": "Habilitations électriques (B1V, B2V, BR, BC)",
    "service.realisation.cta.title": "Un projet de mise en service ?",
    "service.realisation.cta.btn": "Démarrer votre projet",
    "contact.form.phone": "Téléphone",
    "contact.form.company": "Entreprise",
    "contact.form.subject": "Sujet *",
    "contact.form.subject.placeholder": "Sélectionnez un sujet",
    "contact.form.subject.automation": "Automatisme Industriel",
    "contact.form.subject.regulation": "Régulation & Instrumentation",
    "contact.form.subject.electrical": "Installation Électrique",
    "contact.form.subject.maintenance": "Maintenance Industrielle",
    "contact.form.subject.other": "Autre demande",
    "contact.form.message": "Message *",
    "contact.form.message.placeholder": "Décrivez votre projet...",
    "contact.faq.q3": "Quelles marques d'automates supportez-vous ?",
    "contact.faq.a3": "Nous sommes experts sur Siemens (S7, TIA Portal), Schneider (M580, M340), Rockwell et Omron.",
    "contact.faq.q4": "Proposez-vous des contrats de maintenance ?",
    "contact.faq.a4": "Oui, nous proposons des contrats de maintenance préventive et curative sur mesure, adaptés à votre parc machine."
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const t = (key: string) => {
    return (translations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};